server:
  port: 8082
  servlet:
    context-path: /user-service

spring:
  application:
    name: lg-user-service
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: mc_user_service
    show-sql: true
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration
    default-schema: ${spring.jpa.properties.hibernate.default_schema}
application:
  chat:
    websocket:
      anonymous-path: /ws/chat/anonymous
      employee-path: /ws/chat/employee
      ping-retries: 3
      ping-interval: 30s
      message-buffer-size: 8192
      allowed-origins:
        - "*"
      max-session-idle-timeout: 10m
      send-time-limit: 5s

logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.99, 0.95, 0.9, 0.5
